### ISSUE TITLE
KeyError and smtplib.SMTPAuthenticationError

### ISSUE THREAD

**Issue by billybutcher** [saarthdeshpande/book-summarizer#4]
'Corrections'
Traceback (most recent call last):
  File "/content/book-summarizer/model.py", line 107, in summaryGeneration
    summary = sentenceCorrection(summary)
  File "/content/book-summarizer/model.py", line 43, in sentenceCorrection
    sentenceDict = parser.parse(sentence)
  File "/usr/local/lib/python3.7/dist-packages/gingerit/gingerit.py", line 27, in parse
    return self._process_data(text, data)
  File "/usr/local/lib/python3.7/dist-packages/gingerit/gingerit.py", line 39, in _process_data
    for suggestion in reversed(data['Corrections']):
KeyError: 'Corrections'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bsCLI.py", line 20, in <module>
    pdfParser(app.config['PDF_UPLOADS'] + '/pdf_file.pdf')
  File "/content/book-summarizer/preprocess.py", line 96, in pdfParser
    splitChapters(filename, mailid)
  File "/content/book-summarizer/preprocess.py", line 75, in splitChapters
    summaryGeneration(mailid)
  File "/content/book-summarizer/model.py", line 120, in summaryGeneration
    send_fail(mailid)
  File "/content/book-summarizer/mail.py", line 17, in send_fail
    session.login(sender_address, sender_pass)  # login with mail_id and password
  File "/usr/lib/python3.7/smtplib.py", line 730, in login
    raise last_exception
  File "/usr/lib/python3.7/smtplib.py", line 721, in login
    initial_response_ok=initial_response_ok)
  File "/usr/lib/python3.7/smtplib.py", line 642, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials v64sm11061838pfc.117 - gsmtp')

**Comment by saarthdeshpande** [comment]
The username and password you entered at lines 5, 6 in [mails.py](https://github.com/saarthdeshpande/book-summarizer/blob/master/mail.py) are either incorrect or not supported by SMTP.

**Comment by billybutcher** [comment]
> The username and password you entered at lines 5, 6 in [mails.py](https://github.com/saarthdeshpande/book-summarizer/blob/master/mail.py) are either incorrect or not supported by SMTP.

What if I don't want it to mail to me? Doesn't the code just save locally>

**Comment by saarthdeshpande** [comment]
> > The username and password you entered at lines 5, 6 in [mails.py](https://github.com/saarthdeshpande/book-summarizer/blob/master/mail.py) are either incorrect or not supported by SMTP.
> 
> 
> 
> What if I don't want it to mail to me? Doesn't the code just save locally?

If you wish to use without mail, please run:

python3 bsCLI.py --path <path-to-PDF-file>
